rm /etc/ufw/user.rules
rm /etc/ufw/user6.rules
rm /etc/ufw/before.rules
rm /etc/ufw/before6.rules
cd /etc/ufw/
wget https://raw.githubusercontent.com/AQSaikato/abcdxyz-fw/main/user.rules
wget https://raw.githubusercontent.com/AQSaikato/abcdxyz-fw/main/user6.rules
wget https://raw.githubusercontent.com/AQSaikato/abcdxyz-fw/main/before.rules
wget https://raw.githubusercontent.com/AQSaikato/abcdxyz-fw/main/before6.rules
